# Railway Nixpacks configuration for Rust (no Docker)
[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl", "curl"]

[phases.build]
dependsOn = ["setup"]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/ai-interence-server"

[variables]
HOST = "0.0.0.0"
PORT = "3000"
RUST_LOG = "info"
TOKENIZERS_PARALLELISM = "false"
RAYON_NUM_THREADS = "2"
EMBEDDING_CACHE_SIZE = "200"